### ISSUE TITLE
Rspec

### ISSUE THREAD

**Issue by PoloPro** [learn-co-curriculum/rails-generators-readme#10]
In **spec/features/post_spec.rb**, the _post_ instance variable needs a _category_ assigned before testing, since this is required for the view tests

In **spec/models/category_spec.rb**, the test needs to check respond_to on an instance of the _Category_ class (maybe)

RSpec.describe Category, type: :model do
  describe "relations" do
    it 'has many posts' do
      @category = Category.new
      expect(@category).to respond_to(:posts)
    end
  end
end

**Comment by pletcher** [comment]
Fixed with 11a2f32
