### ISSUE TITLE
Naming error in testbank

### ISSUE THREAD

**Issue by xristocodos** [learn-co-curriculum/rails-generators-readme#15]
Post.count
#=> 4
clickbait = Category.find_by(name: "Clickbait")
#=> #<Category id=1>
clickbait.posts.count
#=> 3

Line 3 in db/seeds.rb:
  clickbait = Category.create!(name: "Motivation")

Line 3: in rails console commands, should submit "Motivation" as value, not "Clickbait"
  clickbait = Category.find_by(name: "Clickbait")
should be
  clickbait = Category.find_by(name: "Motivation") #matching the seed
  
clickbait.posts.count will then return 3. otherwise it crashes.

Please see attached.
![bug](https://cloud.githubusercontent.com/assets/10204266/14962044/e089149c-106a-11e6-98f2-e4ae23d79ada.png)

**Comment by pletcher** [comment]
Hi, and thanks for reporting this. Could you confirm that your fork is up to date? I don't see anything in the latest db/seeds.rb.

**Comment by SophieDeBenedetto** [comment]
closing for now. there is no seed file for this lab.
