### ISSUE TITLE
RSpec checks for boolean value of post_status but lab has you set to string

### ISSUE THREAD

**Issue by steveafrost** [learn-co-curriculum/rails-generators-readme#22]
I've submitted an edit to this lesson but it seems more like an issue to me now that I think about it. The lab walks you through changing a column and during that change you set post_status from a boolean to a string. The issue here is that if we do change the column to string type as the lab says, rspec fails because it is looking for a boolean value.

There may need to be a different change_column done or have the rspec check for a string value. Either one of those should fix it up.

**Comment by gj** [comment]
https://github.com/learn-co-curriculum/rails-generators-readme/issues/19#issuecomment-240636345
