### ISSUE TITLE
problem with test

### ISSUE THREAD

**Issue by AdamKing0126** [learn-co-curriculum/rails-generators-readme#3]
A test is improperly written.  It should be modified this way:
```ruby
describe "GET #show" do  
  before do              
    @category = Category.create(name: "hello category")
  end
   
  it "returns http success" do    
    get :show, {:id => @category.id}
    expect(response).to have_http_status(:success)
  end                    
end
```

**Comment by AnnJohn** [comment]
thanks @AdamKing0126. Which test file specifically is this, and could you either send over a screenshot of the incorrect test or the line numbers in the file? Thanks!

**Comment by jmburges** [comment]
I could be wrong, but this doesn't seem like an issue. I searched category in this readme and nothing shows up at all.

**Comment by AdamKing0126** [comment]
Strange.  I have categories_controller_spec but it's not in the github.  Wonder where that came from... Sorry folks.
