### ISSUE TITLE
Is it worth explaining why the create! method is being used, and how it's different from create?

### ISSUE THREAD

**Issue by scirocco21** [learn-co-curriculum/rails-generators-readme#32]
Referring to this line of the read me:

Author.create!(name: "Stephen King", genre: "Horror", bio: "Bio details go here")

**Comment by jenmyers** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
