### ISSUE TITLE
fork/submit not working

### ISSUE THREAD

**Issue by dmcgrann** [learn-co-curriculum/rails-generators-readme#34]
I have forked this lab, run the tests and submitted. But the lab doesn't reflect it. Could you please help? Here is my git repository: https://github.com/dmcgrann/rails-generators-readme-v-000

Thanks.

**Comment by jenmyers** [comment]
Hi there! This request sounds like an improvement to or a problem with the Learn platform.

Raising issues on GitHub, like you've done here should happen when there are problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can to clarify our error, and we will try to find a fix.
