### ISSUE TITLE
Quick Fix: Add word "bio" as a column in table

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/rails-generators-readme#35]
Line 4: Add "bio" since example seems to show it along columns for name and genre
***********************************
Model Generators
This is a generator type that gets used regularly. It does a great job of creating the core code needed to create a model and associated database table without adding a lot of bloat to the application. Let's add a new model to the app called Author with columns name and genre, we can use the model generator with the following CLI command:

rails g model Author name:string genre:string bio:text --no-test-framework

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
