### ISSUE TITLE
Rails Model Generator - rails g model -- Adds application_record.rb

### ISSUE THREAD

**Issue by NYHolzer** [learn-co-curriculum/rails-generators-readme#36]
While following along with the code-along, After invoking the following command: 
`rails g model Author name:string genre:string bio:text --no-test-framework` 
The following resulted:
```
      invoke  active_record
      create    db/migrate/20190618010724_create_authors.rb
      create    app/models/application_record.rb
      create    app/models/author.rb
```
It added an application_record.rb file.
Additionally, class Author inherits from Application Record as such: 
```
class Author < ApplicationRecord
end
```
I believe the material needs to be updated to reflect the changes in Rails 5. I found some information here: https://blog.bigbinary.com/2015/12/28/application-record-in-rails-5.html
and here: https://stackoverflow.com/questions/37359527/why-rails-5-uses-applicationrecord-instead-of-activerecordbase

I think the material in this lesson should be updated accordingly. 
Hoping this will help _learn_ creators to help future _learn_ students.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe this has been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
