### ISSUE TITLE
ForbiddenArgument error on #update

### ISSUE THREAD

**Issue by gzavaglia** [learn-co-curriculum/rails-generators-readme#37]
I kept getting an error after I was done with all my generators and I was able to fix it by changing the `update` method and adding a new method `post_params(*args)`.

```
def update
    # @post = Post.find(params[:id])
    # @post.update(params.require(:post))
    # redirect_to post_path(@post)
    @post = Post.find(params[:id])
    @post.update(post_params(:title))
    redirect_to post_path(@post)
  end

private
	
def post_params(*args)
  params.require(:post).permit(*args)
end
```

This need to be fixed by someone so it won't keep showing errors that are not explained in the readme.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
