### ISSUE TITLE
Different README

### ISSUE THREAD

**Issue by azemoh** [learn-co-curriculum/rails-generators-readme#8]
This lab is about __"Rails generators"__ but the README contains notes about __"Displaying Associations Rails"__. I noticed this because I looked up a lab I had completed and it looked totally different. Compare my [fork](https://github.com/azemoh/rails-generators-readme-v-000) from the previous day. The changes happens on this [commit](https://github.com/learn-co-curriculum/rails-generators-readme/commit/027d6ea239256ac9ff5ae147d9f2c4e2517517d2).

**Comment by pletcher** [comment]
Huh, thanks for reporting this. I'll try to figure out what's going on.

**Comment by PeterBell** [comment]
Hey @pletcher got another report re: this yesterday. Do we just want to revert 027d6ea239256ac9ff5ae147d9f2c4e2517517d2 ? Happy to do it, but wanted to check in with you and @jmburges - either we need to rename the title of the lab or change the content - just let me know what's best and whether I cn help. cc @AnnJohn

**Comment by pletcher** [comment]
Thanks, @PeterBell -- I took your suggestion and reverted the offending commit. Something super crazy happened with this lab -- there might be lingering issues after the revert. I'll keep an eye on things.

And thanks @azemoh for reporting this!

**Comment by PeterBell** [comment]
cc @lukeghenco
